pc - try PUT first then POST

diff --git a/.github/workflows/00-setup-github-pages.yml b/.github/workflows/00-setup-github-pages.yml
--- a/.github/workflows/00-setup-github-pages.yml
+++ b/.github/workflows/00-setup-github-pages.yml
@@ -65,6 +65,16 @@ jobs:
                         https://api.github.com/repos/$REPO/pages \
                         -d '{"source":{"branch":"gh-pages","path":"/"},"build_type": "legacy"}'
 
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to configure GitHub Pages for repository with PUT; trying POST"
+                        curl -sS -L -f -X POST \
+                            -H "Accept: application/vnd.github+json" \
+                            -H "Authorization: Bearer $GITHUB_TOKEN " \
+                            -H "X-GitHub-Api-Version: 2022-11-28" \
+                            https://api.github.com/repos/$REPO/pages \
+                            -d '{"source":{"branch":"gh-pages","path":"/"},"build_type": "legacy"}'
+                    fi
+
             - name: Check configuration
               env:
                 GITHUB_TOKEN: ${{ secrets.PAT }} 
