pc - try adding PUT

diff --git a/.github/workflows/00-setup-github-pages.yml b/.github/workflows/00-setup-github-pages.yml
--- a/.github/workflows/00-setup-github-pages.yml
+++ b/.github/workflows/00-setup-github-pages.yml
@@ -58,8 +58,17 @@ jobs:
                         -H "X-GitHub-Api-Version: 2022-11-28" \
                         https://api.github.com/repos/${{ github.repository}}/pages \
                         -d '{"source":{"branch":"gh-pages","path":"/"}}'; then
-                        echo "Failed to enable GitHub Pages for repository: ${{ github.repository}}"
-                        exit 1
+                        echo "Failed to enable GitHub Pages for repository: ${{ github.repository}} with POST; trying PUT"
+                        if ! curl -sS -L -f -X PUT \
+                            -H "Accept: application/vnd.github+json" \
+                            -H "Content-Type: application/json" \
+                            -H "Authorization: Bearer ${{env.GITHUB_TOKEN}}" \
+                            -H "X-GitHub-Api-Version: 2022-11-28" \
+                            https://api.github.com/repos/${{ github.repository}}/pages \
+                            -d '{"source":{"branch":"gh-pages","path":"/"}}'; then
+                            echo "Failed to enable GitHub Pages for repository: ${{ github.repository}} with PUT"
+                            exit 1
+                        fi
                     fi
                     echo "GitHub Pages enabled for repository: $repo"
             - name: Set repo in "about" section 
