pc - set up better error handling in workflow 00

diff --git a/.github/workflows/00-setup-github-pages.yml b/.github/workflows/00-setup-github-pages.yml
--- a/.github/workflows/00-setup-github-pages.yml
+++ b/.github/workflows/00-setup-github-pages.yml
@@ -50,15 +50,14 @@ jobs:
                 GITHUB_TOKEN: ${{ github.token }} 
               run: |
                     echo "Enabling GitHub Pages for repository:${{ github.repository}}"
-                    curl -sS -L \
-                        --X POST \
+                    if ! curl -sS -L -f -X POST \
                         -H "Accept: application/vnd.github+json" \
+                        -H "Content-Type: application/json" \
                         -H "Authorization: Bearer ${{env.GITHUB_TOKEN}}" \
                         -H "X-GitHub-Api-Version: 2022-11-28" \
                         https://api.github.com/repos/${{ github.repository}}/pages \
-                        -d '{"source":{"branch":"gh-pages","path":"/"}}'
-                    if [ $? -ne 0 ]; then
-                        echo "Failed to enable GitHub Pages for repository: $repo"
+                        -d '{"source":{"branch":"gh-pages","path":"/"}}'; then
+                        echo "Failed to enable GitHub Pages for repository: ${{ github.repository}}"
                         exit 1
                     fi
                     echo "GitHub Pages enabled for repository: $repo"
@@ -67,10 +66,13 @@ jobs:
                  GITHUB_TOKEN: ${{ github.token }} 
               run: |
                     echo "Setting up github pages site on about page for repository: $repo"
-                    curl -X PATCH -H "Authorization: token ${{env.GITHUB_TOKEN}}"  \
+                    curl -sS -f -X PATCH \
                         -H "Accept: application/vnd.github+json" \
-                        https://api.github.com/repos/${{ github.repository}} \
-                        -d "{\"homepage\":\"https://${{ github.repository_owner }} .github.io/${{ github.event.repository.name }}\"}"
+                        -H "Content-Type: application/json" \
+                        -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" \
+                        -H "X-GitHub-Api-Version: 2022-11-28" \
+                        https://api.github.com/repos/${{ github.repository }} \
+                        -d "{\"homepage\":\"https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}\"}"
                     if [ $? -ne 0 ]; then
                         echo "Failed to set github pages site for repository: ${{ github.repository }}"
                         exit 1
